// Generated by uniffi-bindgen-react-native
import installer from './NativeReactNativeProver';

// Register the rust crate with Hermes
// - the boolean flag ensures this loads exactly once, even if the JS
//   code is reloaded (e.g. during development with metro).
let rustInstalled = false;
if (!rustInstalled) {
  installer.installRustCrate();
  rustInstalled = true;
}

// Export the generated bindings to the app.
export * from './generated/midnight_prover';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as midnight_prover from './generated/midnight_prover';

// Initialize the generated bindings: mostly checksums, but also callbacks.
// - the boolean flag ensures this loads exactly once, even if the JS code
//   is reloaded (e.g. during development with metro).
let initialized = false;
if (!initialized) {
  midnight_prover.default.initialize();
  initialized = true;
}

// This provides parity with the index.web.ts version of this file.
// The web version relies on an asynchronous fetch, which this doesn't
// need, so we just no-op.
export async function uniffiInitAsync() {
  // NOOP.
}

// Export the crates as individually namespaced objects.
export default {
  midnight_prover,
};

// ─────────────────────────────────────────────────────────────────
// Hand-written async wrapper around the generated synchronous
// `prove()` binding. Without this, calling `prove()` from JS would
// block the JS thread for the full prove duration (minutes at
// high k). The Promise-based wrapper hands off to a microtask so
// the UI can keep rendering while the Rust side grinds.
//
// Production-grade implementation would run the prove on a worker
// thread (JSI runOnNewThread / TurboModule async path); this
// microtask hand-off is the safe + portable starting point.
// ─────────────────────────────────────────────────────────────────

import type { ProveOptions, ProveResult } from "./generated/midnight_prover";
import { prove as proveSync } from "./generated/midnight_prover";

export interface ProveOptionsPartial {
  /** RNG seed. `0` (the default) = use library default 0x42. */
  seed?: number | bigint;
  /** Skip verifier check after proving. Default `true`. */
  verifyAfter?: boolean;
  /** SRS cache dir override. Empty / undefined = platform default. */
  cacheDir?: string;
  /** Reuse (ProverKey, VerifierKey) pairs across proves. Default `true`. */
  cacheKeys?: boolean;
}

/**
 * Async wrapper around the synchronous generated `prove()`.
 * Returns a Promise so the JS thread can interleave UI work
 * while Rust grinds.
 *
 * @param k log-domain-size of the circuit (1..=21)
 * @param opts optional knobs (all fields have library defaults)
 * @throws ProverError on out-of-range k, params unavailable,
 *         keygen failure, prove failure, IO error, etc.
 */
export async function proveAsync(
  k: number,
  opts: ProveOptionsPartial = {},
): Promise<ProveResult> {
  const filled: ProveOptions = {
    seed: BigInt(opts.seed ?? 0),
    verifyAfter: opts.verifyAfter ?? true,
    cacheDir: opts.cacheDir ?? "",
    cacheKeys: opts.cacheKeys ?? true,
  };
  // Yield to the event loop so any pending UI animations get a
  // frame before we start the multi-minute compute. After the
  // await, control returns synchronously and proveSync blocks
  // until done — the win is purely the initial yield + giving
  // the host a Promise to attach .then() / await to.
  await Promise.resolve();
  return proveSync(k, filled);
}

/** Type guard for `ProverError` instances from the generated bindings. */
export type ProverErrorCode =
  | "OutOfRange"
  | "ParamsUnavailable"
  | "KeygenFailed"
  | "ProveFailed"
  | "VerifyFailed"
  | "Io"
  | "Internal";

export function isProverError(
  e: unknown,
): e is { code: ProverErrorCode; message: string } {
  return (
    typeof e === "object" &&
    e !== null &&
    "code" in e &&
    typeof (e as { code: unknown }).code === "string"
  );
}

