// JSI Turbo Module spec for the native MidnightProver. The actual
// JavaScript binding is auto-generated by `uniffi-bindgen-react-
// native` from `crates/prover-ffi/src/midnight_prover.udl` — the
// command lives in `scripts/build-{ios,android}.sh` as
// `ubrn build {ios|android} --release --and-generate`.
//
// This file is the THIN TypeScript wrapper that imports the
// generated module by its standardised symbol path. The codegen
// places its output under `lib/typescript/native/` after running
// `ubrn`; we re-export it here so the public `src/index.ts` can
// import a stable shape regardless of where ubrn drops the file.
//
// Until `ubrn` is wired into the build, this is a hand-written
// shim that throws — that lets the TS / Jest tooling type-check
// the public surface without the native module being present.

import type { ProveResult } from "./index";

interface ProveOptionsNative {
  seed: bigint;
  verifyAfter: boolean;
  cacheDir: string;
  cacheKeys: boolean;
}

interface NativeMidnightProverModule {
  prove(k: number, opts: ProveOptionsNative): Promise<ProveResult>;
  libraryVersion(): string;
}

// Lazy lookup so we don't crash at import time if the native module
// isn't available (e.g. running Jest in a Node host).
let cached: NativeMidnightProverModule | null = null;

function loadNative(): NativeMidnightProverModule {
  if (cached !== null) return cached;

  // The generated UniFFI binding registers itself on the global
  // JSI bridge under this symbol. In production we'd `import
  // { MidnightProver } from "./native/midnight_prover"` (auto-
  // generated by ubrn). In dev we fall back to a clearly-failing
  // shim so the TS tooling can still type-check.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const global = globalThis as any;
  if (global.__MidnightProver) {
    cached = global.__MidnightProver as NativeMidnightProverModule;
    return cached;
  }

  // Fallback shim — make the failure mode clear.
  cached = {
    prove(_k: number, _opts: ProveOptionsNative): Promise<ProveResult> {
      return Promise.reject(
        new Error(
          "@midnight-ntwrk/react-native-prover: native module not loaded. " +
            "Did you run `yarn build:rust` + `yarn build:ios` / `yarn build:android`? " +
            "On a real device, the autolinking via the package's Podspec / " +
            "build.gradle should have done this for you — check that the " +
            "MidnightProver xcframework is present in the .app bundle " +
            "(iOS) or that libmidnight_prover_ffi.so is in jniLibs (Android).",
        ),
      );
    },
    libraryVersion(): string {
      return "midnight-prover-ffi (native module not loaded)";
    },
  };
  return cached;
}

export const NativeMidnightProver: NativeMidnightProverModule = {
  prove: (k, opts) => loadNative().prove(k, opts),
  libraryVersion: () => loadNative().libraryVersion(),
};
