// Copy upstream WASM-touching packages into ../assets/web/pkg/<name>/
// at build time. Those files are then served by Wry's `mn-pkg://`
// custom protocol (see `dioxus-wallet/src/protocol.rs`) and resolved
// by the WebView's native module + WebAssembly machinery via the
// import map injected from `lib.rs`.
//
// Why vendor instead of bundle: the upstream packages do
//   import * as wasm from "./xxx_bg.wasm";
// which esbuild's `file` loader handles by emitting a URL string,
// breaking wbindgen's module-namespace contract. Native browser
// resolution gets the import right.
//
// **Keep this list in sync** with the `external` list in `build.mjs`
// and the `imports` map in `dioxus-wallet/src/lib.rs::head_html`.

import { build as esbuildBuild } from "esbuild";
import {
  copyFileSync,
  mkdirSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Source repo (cloned outside this workspace).
const SOURCE = resolve(process.env.HOME, "iohk", "midnight-did");
// Where Wry's `mn-pkg://` handler reads from.
const DEST = resolve(__dirname, "..", "assets", "web", "pkg");

// `node_modules/@midnight-ntwrk/<name>` is the resolved tree we copy.
// We pick this over the workspace `<source>/<dir>/` so transitive
// resolution is consistent — every dep already points at the
// resolved version, not a peer that might be a symlink.
const PACKAGES = [
  "midnight-did-contract",
  "compact-runtime",
  "compact-js",
  "onchain-runtime-v3",
  "ledger-v8",
];

function copyDirRecursive(src, dst) {
  mkdirSync(dst, { recursive: true });
  for (const entry of readdirSync(src)) {
    // Skip dev artifacts and nested node_modules; we resolve those
    // via the import map at runtime, not via package-internal trees.
    if (
      entry === "node_modules" ||
      entry === "coverage" ||
      entry === "reports" ||
      entry === ".turbo" ||
      entry.endsWith(".tgz")
    ) {
      continue;
    }
    const s = join(src, entry);
    const d = join(dst, entry);
    if (statSync(s).isDirectory()) {
      copyDirRecursive(s, d);
    } else {
      copyFileSync(s, d);
    }
  }
}

console.log(`[vendor] source: ${SOURCE}`);
console.log(`[vendor] dest:   ${DEST}`);

rmSync(DEST, { recursive: true, force: true });
mkdirSync(DEST, { recursive: true });

let total = 0;
for (const pkg of PACKAGES) {
  const src = resolve(SOURCE, "node_modules", "@midnight-ntwrk", pkg);
  const dst = resolve(DEST, pkg);
  try {
    statSync(src);
  } catch (_) {
    console.error(`[vendor] missing source: ${src}`);
    process.exit(1);
  }
  copyDirRecursive(src, dst);
  total++;
  console.log(`[vendor]   ✓ ${pkg}`);
}

// Some upstream packages (compact-runtime → object-inspect) reach
// for third-party CJS modules the WebView's native ESM loader can't
// load directly. We esbuild-bundle each into an ESM wrapper, place
// it under pkg/<name>/index.js, and route the import map at it.
//
// Keep the list in sync with the import map in
// `dioxus-wallet/src/lib.rs::head_html`.
const CJS_DEPS = [
  "object-inspect",
];

for (const dep of CJS_DEPS) {
  const src = resolve(SOURCE, "node_modules", dep);
  const dst = resolve(DEST, dep);
  try {
    statSync(src);
  } catch (_) {
    console.error(`[vendor] missing CJS dep: ${src}`);
    process.exit(1);
  }
  mkdirSync(dst, { recursive: true });
  await esbuildBuild({
    entryPoints: [resolve(src, "index.js")],
    bundle: true,
    format: "esm",
    platform: "browser",
    outfile: resolve(dst, "index.js"),
    logLevel: "warning",
  });
  total++;
  console.log(`[vendor]   ✓ ${dep} (CJS→ESM)`);
}

// Replace the wbindgen entry file with a browser-compatible loader.
// The default `xxx.js` file does `import * as wasm from "./xxx.wasm"`,
// which requires WebAssembly ES Module Integration (a stage-4 spec
// not yet enabled in WKWebView). We swap it for a manual loader that
// fetches the .wasm via `import.meta.url`, instantiates with the
// `_bg.js`-supplied imports table, then calls `__wbg_set_wasm` +
// `__wbindgen_start` exactly like the upstream Node loader does
// (`xxx_fs.js`).
function rewriteWbindgenEntry(packageDir, entryStem) {
  const entryPath = resolve(packageDir, `${entryStem}.js`);
  const bgFile = `./${entryStem}_bg.js`;
  const wasmFile = `./${entryStem}_bg.wasm`;
  const browserLoader = `// Auto-generated by web/vendor.mjs at build time.
// Replaces upstream's \`import * as wasm from "${wasmFile}"\` (which
// needs WebAssembly ESM Integration) with a fetch + manual
// instantiation. Mirrors xxx_fs.js for Node, but fetches over the
// \`mn-pkg://\` protocol via \`import.meta.url\` resolution.

import * as bgExports from "${bgFile}";
export * from "${bgFile}";
import { __wbg_set_wasm } from "${bgFile}";

const imports = {};
imports["${bgFile}"] = bgExports;

const wasmUrl = new URL("${wasmFile}", import.meta.url);
const response = await fetch(wasmUrl);
let instance;
if (typeof WebAssembly.instantiateStreaming === "function") {
  try {
    ({ instance } = await WebAssembly.instantiateStreaming(response, imports));
  } catch (_e) {
    const bytes = await (await fetch(wasmUrl)).arrayBuffer();
    ({ instance } = await WebAssembly.instantiate(bytes, imports));
  }
} else {
  const bytes = await response.arrayBuffer();
  ({ instance } = await WebAssembly.instantiate(bytes, imports));
}
const wasm = instance.exports;

__wbg_set_wasm(wasm);
wasm.__wbindgen_start();
`;
  writeFileSync(entryPath, browserLoader);
  console.log(`[vendor]   ↻ ${entryPath.split("/").slice(-2).join("/")} (wbindgen rewrite)`);
}

const WBINDGEN_ENTRIES = [
  ["onchain-runtime-v3", "midnight_onchain_runtime_wasm"],
  ["ledger-v8", "midnight_ledger_wasm"],
];
for (const [pkg, stem] of WBINDGEN_ENTRIES) {
  rewriteWbindgenEntry(resolve(DEST, pkg), stem);
}

console.log(`[vendor] copied ${total} package(s).`);
