// This file is part of midnight-ledger.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Every compiled-in verifying key must use a version the proving path routes.
//! Built-in keys remain `v6`, so they use the pre-accumulator `V2` path.

#![deny(warnings)]

use serialize::peek_tag;

/// The tags `ContractCallPrototype::prove` matches on.
const ROUTABLE: [&str; 2] = ["verifier-key[v6]", "verifier-key[v8]"];

/// Read through `include_bytes!` so this tracks the compiled-in keys.
const SHIPPED: [(&str, &[u8]); 4] = [
    (
        "zswap/static/output.verifier",
        include_bytes!("../../zswap/static/output.verifier"),
    ),
    (
        "zswap/static/spend.verifier",
        include_bytes!("../../zswap/static/spend.verifier"),
    ),
    (
        "zswap/static/sign.verifier",
        include_bytes!("../../zswap/static/sign.verifier"),
    ),
    (
        "ledger/static/dust/spend.verifier",
        include_bytes!("../static/dust/spend.verifier"),
    ),
];

#[test]
fn every_shipped_verifier_key_has_a_routable_tag() {
    for (name, bytes) in SHIPPED {
        let tag = peek_tag(&mut std::io::Cursor::new(bytes))
            .unwrap_or_else(|e| panic!("{name}: peek tag: {e}"));
        assert!(
            ROUTABLE.contains(&tag.as_str()),
            "{name} carries '{tag}', which `ContractCallPrototype::prove` does not route; \
             proving with this key would fail at runtime with UnknownVerifierKeyVersion. \
             Either the router needs the new tag, or this key was regenerated by accident."
        );
    }
}

#[test]
fn the_shipped_keys_are_all_pre_accumulator() {
    // Pins the assumption the `V2` branch rests on: it discards
    // `proof.accumulators`, which is only safe while no shipped key can carry
    // them. If this fails, a built-in circuit has moved to the v3 toolchain and
    // that branch needs to refuse a non-empty accumulator vector rather than
    // drop it silently.
    for (name, bytes) in SHIPPED {
        let tag = peek_tag(&mut std::io::Cursor::new(bytes))
            .unwrap_or_else(|e| panic!("{name}: peek tag: {e}"));
        assert_eq!(
            tag, "verifier-key[v6]",
            "{name} is no longer a pre-accumulator key; see this test's doc comment"
        );
    }
}
