[workspace]
package.license = "Apache-2.0"
package.repository = "https://github.com/midnightntwrk/midnight-ledger"
members = [
    "onchain-runtime",
]
default-members = [
    "onchain-runtime",
]
resolver = "2"
exclude = [
    "scripts/hardfork_version_patch"
]

# Pretty much every dependency is crypto.
# If there's one thing I know about it, it's that we don't want the molasses
# of unoptimized crypto.
[profile.dev.package."*"]
opt-level = 2
[profile.test.package."*"]
opt-level = 2

[profile.wasm]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[workspace.metadata.spellcheck]
config = ".spellcheck/cargo-spellcheck.toml"

[patch.crates-io]
midnight-serialize = { path = "serialize" }
