[package]
name = "midnight-zswap"
edition = "2024"
version = "9.0.0"
license.workspace = true
repository.workspace = true
description = "Implementation of the Zswap shielded token atomic swap mechanism."

[features]
default = ["proof-verifying"]
proof-verifying = ["dep:zkir_v2"]

[dependencies]
base-crypto = { version = "1.1.0", package = "midnight-base-crypto" }
transient-crypto = { version = "3.0.0", package = "midnight-transient-crypto" }
transient-crypto-old = { package = "midnight-transient-crypto", version = "^2.0.0" }
anyhow = "^1.0.102"
coin-structure = { version = "3.0.0", package = "midnight-coin-structure" }
storage = { version = "2.0.0", package = "midnight-storage" }
serialize = { version = "1.0.0", package = "midnight-serialize" }
midnight-onchain-runtime = { version = "4.0.0", package = "midnight-onchain-runtime", features = [ "vendored" ] }
midnight-ledger-static = { version = "9.0.0", package = "midnight-ledger-static" }

# rand 0.9.0 is not yet supported by some of our dependencies, we will
# stick with 0.8.0 for now.
rand = { version = "^0.8.4", features = ["getrandom"] }
is_sorted = "^0.1.1"
lazy_static = "^1.5.0"
tracing = { version = "^0.1.41" }
itertools = "^0.14.0"
zeroize = "^1.8.0"

zkir_v2 = { version = "2.2.0", package = "midnight-zkir", optional = true }

fake = { version = "^2.10.0", features = ["derive"] }
futures = { version = "^0.3.31" }
serde = { version = "^1.0.219", features = ["derive"] }
derive-where = "^1.6.1"

[[bench]]
name = "benchmarking"
harness = false
