// This file is part of midnight-ledger.
// Copyright (C) Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Backwards compatibility test: verifies that a proof created with zk-stdlib v1
//! (old transient-crypto from crates.io) can be verified with zk-stdlib v2
//! (current transient-crypto).
//!
//! The test fixtures in `tests/v1_fixtures/` were generated by the standalone
//! `tests/v1_proof_generator/` crate, which uses `midnight-transient-crypto 2.0.1`
//! and `midnight-zkir 2.1.0` from crates.io (both using zk-stdlib v1).
//!
//! The circuit is a minimal assert circuit with 1 input (binding_input = 42),
//! producing a statement of `[Fr::from(42)]`.
//!
//! To regenerate fixtures (if the old version changes):
//!   cd tests/v1_proof_generator && cargo run

#[cfg(test)]
mod tests {
    use midnight_transient_crypto::curve::Fr;
    use midnight_transient_crypto::proofs::{Proof, VerifierKey, PARAMS_VERIFIER};
    use serialize::Deserializable;

    fn load_v1_fixtures() -> (Proof, VerifierKey, Vec<Fr>) {
        let proof_bytes = include_bytes!("v1_fixtures/proof.bin");
        let vk_bin = include_bytes!("v1_fixtures/vk.bin");
        let statement_json = include_str!("v1_fixtures/statement.json");

        let proof = Proof(proof_bytes.to_vec());
        let vk: VerifierKey =
            Deserializable::deserialize(&mut &vk_bin[..], 0).expect("VK deserialization failed");
        let statement: Vec<Fr> =
            serde_json::from_str(statement_json).expect("statement deserialization failed");

        (proof, vk, statement)
    }

    #[test]
    fn v1_vk_deserializes_and_initializes() {
        let (_, vk, _) = load_v1_fixtures();
        vk.init()
            .expect("VK from v1 should initialize with v2");
    }

    #[test]
    fn v1_proof_verifies_with_v2() {
        let (proof, vk, statement) = load_v1_fixtures();

        vk.verify(&PARAMS_VERIFIER, &proof, statement.into_iter())
            .expect("proof created with zk-stdlib v1 should verify with zk-stdlib v2");
    }

    #[test]
    fn v1_proof_rejects_wrong_statement_with_v2() {
        let (proof, vk, _) = load_v1_fixtures();

        let wrong_statement = vec![Fr::from(43)];
        assert!(
            vk.verify(&PARAMS_VERIFIER, &proof, wrong_statement.into_iter())
                .is_err(),
            "v1 proof should reject wrong statement with v2 verifier"
        );
    }
}
