# CocoaPods spec for the iOS side of @midnight-ntwrk/react-native-prover.
#
# RN autolinking picks this up via the `package.json`. The host
# RN app's `pod install` (or `npx pod-install`) wires the
# xcframework into the build automatically.

require "json"
package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = "MidnightProver"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = "https://github.com/midnightntwrk/midnight-ledger"
  s.license      = "Apache-2.0"
  s.authors      = "Midnight Foundation"

  s.platforms    = { :ios => "14.0" }
  s.source       = { :git => "https://github.com/midnightntwrk/midnight-ledger.git", :tag => "react-native-prover-#{s.version}" }

  # Swift wrapper sources generated by `ubrn build ios` end up
  # under `ios/Sources/`; include them all.
  s.source_files = "ios/Sources/**/*.{h,m,mm,swift}"

  # The xcframework wraps the Rust .a slices.
  s.vendored_frameworks = "ios/MidnightProver.xcframework"

  s.dependency "React-Core"

  # JSI / Fabric / Turbo Module shape. Mirrors what `create-react-
  # native-library` emits for a 0.74 Turbo Module.
  install_modules_dependencies(s)
end
