// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "midnight-ntwrk-react-native-prover.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNNativeModuleSpec.h"

@interface ReactNativeProver : NSObject <NativeReactNativeProverSpec>
#else
#import <React/RCTBridgeModule.h>

@interface ReactNativeProver : NSObject <RCTBridgeModule>
#endif

@end