// Generated by uniffi-bindgen-react-native
#include <jni.h>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvokerHolder.h>
#include "midnight-ntwrk-react-native-prover.h"

namespace jsi = facebook::jsi;
namespace react = facebook::react;

// Automated testing checks Java_com_midnightntwrk_reactnativeprover_ReactNativeProverModule and midnightntwrk_reactnativeprover
// by comparing the whole line here.
/*
Java_com_midnightntwrk_reactnativeprover_ReactNativeProverModule_nativeMultiply(JNIEnv *env, jclass type, jdouble a, jdouble b) {
    return midnightntwrk_reactnativeprover::multiply(a, b);
}
*/

// Installer coming from ReactNativeProverModule
extern "C"
JNIEXPORT jboolean JNICALL
Java_com_midnightntwrk_reactnativeprover_ReactNativeProverModule_nativeInstallRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    using JCallInvokerHolder = facebook::react::CallInvokerHolder;

    auto holderLocal = facebook::jni::make_local(callInvokerHolderJavaObj);
    auto holderRef = facebook::jni::static_ref_cast<JCallInvokerHolder::javaobject>(holderLocal);
    auto* holderCxx = holderRef->cthis();
    auto jsCallInvoker = holderCxx->getCallInvoker();
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);

    return midnightntwrk_reactnativeprover::installRustCrate(*runtime, jsCallInvoker);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_midnightntwrk_reactnativeprover_ReactNativeProverModule_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return midnightntwrk_reactnativeprover::cleanupRustCrate(*runtime);
}