#ifndef MIDNIGHTNTWRK_REACTNATIVEPROVER_H
#define MIDNIGHTNTWRK_REACTNATIVEPROVER_H
// Generated by uniffi-bindgen-react-native
#include <cstdint>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvoker.h>

namespace midnightntwrk_reactnativeprover {
  using namespace facebook;

  uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker);
  uint8_t cleanupRustCrate(jsi::Runtime &runtime);
}

#endif /* MIDNIGHTNTWRK_REACTNATIVEPROVER_H */