// Generated by uniffi-bindgen-react-native
#include "midnight-ntwrk-react-native-prover.h"
#include "generated/midnight_prover.hpp"

namespace midnightntwrk_reactnativeprover {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeMidnightProver::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}