dev_comments = false
skip_readme = false

[hunspell]
lang = "en_US"
search_dirs = ["."]
skip_os_lookups = false
use_builtin = true
tokenization_splitchars = '''",;:.!?#(){}[]|/_-‒'`&@§¶…'''
extra_dictionaries = ["./extra-words.dic"]

[hunspell.quirks]
transform_regex = []
allow_concatenation = false
allow_dashes = false
allow_emojis = true
check_footnote_references = true

[zet]
lang = "en_US"
search_dirs = ["."]
skip_os_lookups = false
use_builtin = true
tokenization_splitchars = '''",;:.!?#(){}[]|/_-‒'`&@§¶…'''
extra_dictionaries = ["./extra-words.dic"]

[zet.quirks]
transform_regex = []
allow_concatenation = false
allow_dashes = false
allow_emojis = true
check_footnote_references = true

[spellbook]
lang = "en_US"
search_dirs = ["."]
skip_os_lookups = false
use_builtin = true
tokenization_splitchars = '''",;:.!?#(){}[]|/_-‒'`&@§¶…'''
extra_dictionaries = ["./extra-words.dic"]

[spellbook.quirks]
transform_regex = []
allow_concatenation = false
allow_dashes = false
allow_emojis = true
check_footnote_references = true

[nlprules]

[reflow]
max_line_length = 80
