//! UniFFI bindings around `contract-benchmark`'s prove path.
//!
//! Design: keep the FFI surface narrow and async-free at the Rust
//! boundary so we don't trip the
//! [`uniffi-bindgen-react-native` deadlock bugs](https://github.com/jhugman/uniffi-bindgen-react-native/pull/88).
//! The internal `tokio::Runtime::block_on` runs the async
//! `run_proof_with_opts` synchronously on a worker thread that
//! the platform layer (Swift / Kotlin) wraps in its own
//! `Promise` / `Coroutine` / `Combine` async primitive.
//!
//! This is intentionally Option A from the architecture doc's §13.4
//! — same-process FFI on BOTH iOS and Android. No `:proverProcess`
//! Service; no separate-process isolation. The trade-off: a 4 GiB+
//! prove OOM in the prover crashes the RN host app on Android too.
//! Documented in the package README + the architecture doc.

use std::path::PathBuf;
use std::sync::OnceLock;

use contract_benchmark::{RunOpts as InnerOpts, RunStats, run_proof_with_opts};
use thiserror::Error;
use tokio::runtime::Runtime;

// Wallet / keys / DID surface — gated on the `wallet` feature so
// consumers who only need proving can drop the wallet-core dep.
#[cfg(feature = "wallet")]
mod wallet;
#[cfg(feature = "wallet")]
pub use wallet::{
    KeyInfo, Wallet, WalletError, did_deactivate, did_deploy, did_resolve, did_update_aka,
    probe_connectivity,
};

// Generated by `uniffi::generate_scaffolding` (see `build.rs`).
uniffi::include_scaffolding!("midnight_prover");

#[derive(Error, Debug)]
pub enum ProverError {
    #[error("k out of supported range")]
    OutOfRange,
    #[error("BLS params unavailable for this k")]
    ParamsUnavailable,
    #[error("keygen failed: {0}")]
    KeygenFailed(String),
    #[error("prove failed: {0}")]
    ProveFailed(String),
    #[error("verify failed: {0}")]
    VerifyFailed(String),
    #[error("io: {0}")]
    Io(String),
    #[error("internal: {0}")]
    Internal(String),
}

/// Options dictionary mirrored from `contract-benchmark::RunOpts` for
/// UniFFI consumption. Flattened so the TS side doesn't have to deal
/// with `Option<PathBuf>` round-trips.
#[derive(Debug, Clone)]
pub struct ProveOptions {
    pub seed: u64,
    pub verify_after: bool,
    pub cache_dir: String,
    pub cache_keys: bool,
}

impl ProveOptions {
    fn into_inner(self) -> InnerOpts {
        InnerOpts {
            // `seed = 0` is the TS-side "use default" sentinel — map
            // to the InnerOpts default (0x42, see RunOpts::default).
            seed: if self.seed == 0 { 0x42 } else { self.seed },
            verify_after: self.verify_after,
            cache_dir: if self.cache_dir.is_empty() {
                None
            } else {
                Some(PathBuf::from(self.cache_dir))
            },
            cache_keys: self.cache_keys,
        }
    }
}

/// Outcome dictionary mirrored from `contract-benchmark::RunStats`.
/// Durations are milliseconds (u64) — see UDL for rationale.
#[derive(Debug, Clone)]
pub struct ProveResult {
    pub k: u32,
    pub realized_k: u32,
    pub hash_chain_len: u32,
    pub rows: u64,
    pub keygen_ms: u64,
    pub prove_ms: u64,
    pub verify_ms: Option<u64>,
    pub verified: Option<bool>,
    pub proof_bytes: u64,
}

impl From<RunStats> for ProveResult {
    fn from(s: RunStats) -> Self {
        Self {
            k: s.k,
            realized_k: s.realized_k,
            hash_chain_len: s.hash_chain_len,
            rows: s.rows,
            keygen_ms: s.keygen.as_millis() as u64,
            prove_ms: s.prove.as_millis() as u64,
            verify_ms: s.verify.map(|d| d.as_millis() as u64),
            verified: s.verified,
            proof_bytes: s.proof_bytes as u64,
        }
    }
}

/// Rayon thread-pool configuration. Done once, lazily, on the
/// first FFI call. Default: `max(1, num_cpus - 1)` — reserves one
/// core for the OS / UI / JS thread so the host app stays
/// responsive while the prover crunches. The consumer can
/// override via `configure_threads(N)` BEFORE any prove call.
///
/// `rayon::ThreadPoolBuilder::build_global()` can only succeed
/// once; the first config wins. We silently swallow the
/// already-initialized error because the second-init-wins
/// behaviour is benign for our case (it just means rayon was
/// already up via another path).
pub(crate) fn ensure_rayon_configured(num_threads: usize) {
    static RAYON_CONFIGURED: std::sync::OnceLock<()> = std::sync::OnceLock::new();
    RAYON_CONFIGURED.get_or_init(|| {
        let _ = rayon::ThreadPoolBuilder::new()
            .num_threads(num_threads.max(1))
            .thread_name(|i| format!("midnight-rayon-{i}"))
            .build_global();
    });
}

/// Install rustls' `ring` crypto provider as the process default.
///
/// rustls 0.23 requires an explicit `CryptoProvider` installed
/// before any TLS handshake. The transitive dep tree compiles
/// in BOTH `aws-lc-rs` (via some indirect deps) and `ring` (via
/// reqwest/tokio-tungstenite), and rustls picks neither by
/// default. The first TLS use then either panics ("no default
/// provider") or — on Android — segfaults inside aws-lc-rs's
/// jitter-entropy initialization (`jent_entropy_collector_alloc`
/// landing on an uninitialized function pointer in BSS).
///
/// Picking `ring` explicitly keeps us pure-Rust on every target,
/// no C / aws-lc compile, and dodges the entropy-init crash.
/// Idempotent — the underlying `install_default()` only succeeds
/// once.
pub(crate) fn ensure_default_crypto_provider() {
    static ONCE: std::sync::Once = std::sync::Once::new();
    ONCE.call_once(|| {
        let _ = rustls::crypto::ring::default_provider().install_default();
    });
}

fn default_num_threads() -> usize {
    // Leave 1 core for the OS / UI / JS thread. On dual-core
    // devices this floors at 1 (single-threaded prove); on
    // 6-core iPhones we use 5; on the M-series host we use 7.
    num_cpus::get().saturating_sub(1).max(1)
}

/// Override the rayon thread count. Must be called BEFORE any
/// `prove()`, `did_resolve()`, or other compute-heavy FFI
/// function — once rayon's global pool is initialised, the
/// thread count is locked in for the process lifetime.
///
/// `0` means "use the default" (num_cpus - 1). Any positive
/// integer sets that explicit thread count. Values above
/// `num_cpus` are accepted but oversubscribe.
pub fn configure_threads(num_threads: u32) {
    let n = if num_threads == 0 {
        default_num_threads()
    } else {
        num_threads as usize
    };
    ensure_rayon_configured(n);
}

/// Returns the configured rayon thread count. Useful for UI
/// telemetry — the demo's About screen displays this so devs
/// can confirm the (cores - 1) default applied.
pub fn rayon_threads() -> u32 {
    rayon::current_num_threads() as u32
}

/// Process-wide tokio runtime — re-used across every prove call so
/// we don't pay thread-pool init per FFI invocation. `OnceLock`
/// because UniFFI's generated code calls our functions from many
/// JS contexts and a static is the simplest single-init pattern.
fn runtime() -> &'static Runtime {
    static RT: OnceLock<Runtime> = OnceLock::new();
    RT.get_or_init(|| {
        tokio::runtime::Builder::new_multi_thread()
            .enable_all()
            .thread_name("midnight-prover")
            .build()
            .expect("init tokio runtime for midnight-prover-ffi")
    })
}

/// Run a single bench prove at the requested `k`.
///
/// The call **blocks the caller** until the proof completes, but
/// the actual work runs on a freshly-spawned worker thread with a
/// generous (16 MiB) stack. Critical for React Native: the JSI host
/// function fires on the JS thread, whose default stack is ~1 MiB
/// on iOS — and halo2's keygen/prove paths recurse deeper than that
/// almost immediately. Without the offload the app crashes with
/// EXC_BAD_ACCESS / "Thread stack size exceeded" on the first prove.
///
/// The implementation lives in `contract-benchmark` and is the same
/// path the dioxus-wallet exercises from its Bench tab. RNG seed
/// 0 means "use default" (matches the UDL contract). The matching
/// declaration lives in `midnight_prover.udl`.
pub fn prove(k: u32, opts: ProveOptions) -> Result<ProveResult, ProverError> {
    // Apply the default rayon thread count if the consumer
    // hasn't already called `configure_threads(N)`. Idempotent —
    // does nothing if rayon's global pool was already initialised
    // (either by us on a prior call, or by an external dep that
    // touched rayon first).
    ensure_rayon_configured(default_num_threads());
    // Must be installed BEFORE MidnightDataProvider::new — that ctor
    // builds a reqwest::Client, which in turn touches rustls. On
    // Android the aws-lc-rs entropy init crashes if ring isn't the
    // installed default. See ensure_default_crypto_provider().
    ensure_default_crypto_provider();
    let inner = opts.into_inner();

    // Sized for halo2 prove at k≈20+. 16 MiB is the same ballpark
    // dioxus-wallet uses on phone — comfortable headroom above what
    // we've observed sticking. The worker joins synchronously so
    // we don't leak threads on early returns.
    const PROVE_STACK_BYTES: usize = 16 * 1024 * 1024;
    let handle = std::thread::Builder::new()
        .name("midnight-prover-worker".into())
        .stack_size(PROVE_STACK_BYTES)
        .spawn(move || runtime().block_on(run_proof_with_opts(k, inner)))
        .map_err(|e| ProverError::ProveFailed(format!("spawn prover worker: {e}")))?;
    let result: Result<RunStats, _> = handle
        .join()
        .map_err(|_| ProverError::ProveFailed("prover worker panicked".to_string()))?;

    result.map(Into::into).map_err(|e| {
        // `contract_benchmark::Error` is structured but the discriminant
        // info is mostly useful for telemetry. Collapse to a single
        // `ProveFailed` variant carrying the printable error chain
        // until a downstream consumer asks for finer-grained mapping.
        let s = format!("{:#}", e);
        if s.contains("k out of range") {
            ProverError::OutOfRange
        } else if s.contains("could not build a circuit") {
            ProverError::KeygenFailed(s)
        } else if s.contains("Io") || s.contains("io error") {
            ProverError::Io(s)
        } else {
            ProverError::ProveFailed(s)
        }
    })
}

/// SemVer + git-sha-pinned version of this FFI crate. Lets the TS
/// side log which Rust core it's bound to (`@midnight-ntwrk/react-
/// native-prover` package version is independently bumped, so an
/// older npm install paired with a never-rebuilt native dylib
/// would show up as a mismatch here). The matching UDL declaration
/// lives in `midnight_prover.udl`.
pub fn library_version() -> String {
    format!("midnight-prover-ffi {}", env!("CARGO_PKG_VERSION"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn library_version_includes_crate_name() {
        let v = library_version();
        assert!(v.contains("midnight-prover-ffi"));
        assert!(v.contains(env!("CARGO_PKG_VERSION")));
    }

    #[test]
    fn prove_options_into_inner_translates_empty_cache_dir_to_none() {
        let opts = ProveOptions {
            seed: 0,
            verify_after: true,
            cache_dir: String::new(),
            cache_keys: true,
        };
        let inner = opts.into_inner();
        assert!(inner.cache_dir.is_none());
        // seed=0 means "use default" — RunOpts::default seed is 0x42.
        assert_eq!(inner.seed, 0x42);
    }
}
